spring:
  application:
    name: ${APPLICATION_NAME}

  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yml
        namespace: ${YOUR_NAMESPACE}
        group: ${YOUR_GROUP}

      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.cloud.nacos.config.namespace}
        group: ${spring.cloud.nacos.config.group}
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
      # mysql、mybatis
      - optional:nacos:mysql.yml?group=${spring.cloud.nacos.config.group}&refresh=true